use Trab_Final
go

insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Palio','1',39900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Linea','1',35900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Hilux','1',80000.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Étios','1',47500.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Fiesta','1',24700.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Ecosport','1',32000.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Prisma','1',45900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Captiva','1',50600.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('City','1',41600.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Civic','1',22900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('206','1',12400.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('308','1',86900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Duster','1',50900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Megane','1',25900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Beetle','1',50000.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Golf','1',33900.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Pastilha de freio','2',94.90,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Kit de Embreagem','2',186.34,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Interruptor de pressão do óleo','2',27.67,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Bobina de ignição','2',125.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Atuador de marcha lenta','2',71.92,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Cabo de vela','2',96.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Parabrisas','4',350.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('ParaLamas','4',450.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Parachoque','4',500.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Pneus','4',250.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Calotas','4',600.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Rodas','4',1500.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Rádio','5',800.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Alarme','5',450.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Macaco','5',350.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Lâmpadas','2',50.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Capas para banco','6',200.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Tapetes','6',250.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Martelinho de Ouro','3',450.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Enceramento','3',250.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Lavagem','3',50.00,GETDATE())
insert into TB_PRODUTOS(nome_prod, grupo_prod, preco_prod, data_cadastro) values('Alinhamento de eixo','3',350.00,GETDATE())
go

select * from TB_PRODUTOS